### ISSUE TITLE
Workers using AMQP driver only process the first batch of messages

### ISSUE THREAD

**Issue by cavalle** [cavalle/eventwire#24]
It looks like, after the first Eventmachine loop, workers using the AMQP driver don't process any further message

**Comment by hallgren** [comment]
Does it work in the ampq_only branch?

It seams that you use EventMachine in that branch but not in the master in the ampq driver.

https://github.com/cavalle/eventwire/blob/amqp_only/lib/eventwire/drivers/amqp.rb

**Comment by cavalle** [comment]
This issue needs more investigation. I don't know exactly when or where it works. The amqp_only branch is work in progress. In the master branch we use `AMQP.start` which executes `EM.run`.

**Comment by hallgren** [comment]
Can your problem have anything to do with the issue I posted on the banksimplistic project?

https://github.com/cavalle/banksimplistic/issues/3

I use an self made amqp driver using the EMWrapper code and it works nicely.

**Comment by cavalle** [comment]
I don't know. As I told you this needs investigation: first reproduce the problem with a test, then find the cause and fix it. Patches are welcome :)

**Comment by hallgren** [comment]
I hade the problem that the connection to the rabbitMQ-server on the worker was still open after worker exit. And rabbitMQ still pushed messages to the (dead) client.

I added this statement to the tasks.rb file 

trap('TERM') { Eventwire.stop_worker; exit }

Hope it helps.

**Comment by cavalle** [comment]
I don't know what you mean. That statement is in [tasks.rb](https://github.com/cavalle/eventwire/blob/master/lib/eventwire/tasks.rb) since 2 months ago. Anyway, it seems completely unrelated to this issue.

**Comment by cavalle** [comment]
ok, investigated this and been unable to reproduce the original problem. I'm suspecting I had a problem with the version of the AMQP gem. 

Closing the issue
